#!/usr/bin/env python3
"""
run_local.py — offline runner for generate_rsvp.py
Injects pre-fetched HubSpot contact data (from MCP) so the generator
can build the HTML without direct network access to api.hubapi.com.
"""

import json
import os
import sys

# Load .env if present (keeps secrets out of version control)
_env_path = os.path.join(os.path.dirname(__file__), '.env')
if os.path.exists(_env_path):
    for _line in open(_env_path):
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _v = _line.split('=', 1)
            os.environ.setdefault(_k.strip(), _v.strip())

os.environ.setdefault('DAYS_BACK', '3')

ENRICHMENTS = {
    "224364188294": {"jobtitle": "Corporate Sales Representative", "company": "SweetGiftsbyStar"},
    "224349365265": {"jobtitle": "Attorney",                       "company": "Law Offices of Judith Vargas"},
    "224349822515": {"jobtitle": "Senior Vice President, Balance Sheet Construction", "company": "Merchants Capital"},
    "224345827471": {"jobtitle": "Managing Director",              "company": "Deutsche Bank"},
    "224365697445": {"jobtitle": "Photographer"},
}

CONTACTS = [
  # ── Batch 1 ───────────────────────────────────────────────────────────────
  {"id":"474557801","properties":{"firstname":"Kenneth","lastname":"Sullivan","email":"nykenny@gmail.com","jobtitle":"Owner","company":"Kenco Designs","phone":"+12128663000","city":"bellmore","state":"NY","zip":"10001","address":"1524 broad st","hubspot_owner_id":"77771452","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":"0","createdate":"2023-08-25T23:24:42.745Z","hs_v2_date_entered_current_stage":"2026-05-27T20:36:16.938Z","wealth_segment":"$5M-$10M","inferred_income":"$251k - $500k","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"nykenny@gmail.com","pipl_linkedin":"linkedin.com/in/kennysullivan"}},
  {"id":"223239896625","properties":{"firstname":"Betsy","lastname":"Colucci","email":"betsy.colucci@wellsfargo.com","jobtitle":"Executive Director, Enterprise Counterparty Risk Management","company":"Wells Fargo","phone":"+19175178402","city":"New York City","state":None,"zip":None,"address":None,"hubspot_owner_id":"73613833","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.231Z","hs_v2_date_entered_current_stage":"2026-05-27T21:17:36.228Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"betsy.colucci@wellsfargo.com","pipl_linkedin":"https://www.linkedin.com/in/betsy-colucci"}},
  {"id":"44705939008","properties":{"firstname":"Sucharita","lastname":"Dasa","email":"sucharita.e.dasa@gmail.com","jobtitle":"Managing Director, Investment Banking, Clean Energy Transition","company":"Citi","phone":"+1 (917) 575-3741","city":"new york","state":"NY","zip":"10001","address":"250 e 54th st","hubspot_owner_id":"77771452","lifecyclestage":"customer","call_completed":"Meeting within 14 days","outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":"0","createdate":"2024-06-19T16:55:47.832Z","hs_v2_date_entered_current_stage":"2024-10-04T13:58:40.554Z","wealth_segment":"$10M-$20M","inferred_income":"$1M+","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"sucharita.e.dasa@gmail.com","pipl_linkedin":"https://www.linkedin.com/in/sucharita-e-dasa"}},
  {"id":"223238970885","properties":{"firstname":"Art","lastname":"Spice","email":"plus_one_rsvp_artspice@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:47:46.836Z","hs_v2_date_entered_current_stage":"2026-05-22T13:47:46.836Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"djpelau@gmail.com","work_email":"Plus_One_RSVP_ArtSpice@gmail.com","pipl_linkedin":None}},
  {"id":"131102201","properties":{"firstname":"Richard","lastname":"Allin","email":"rcallinjr@gmail.com","jobtitle":"Chief Revenue Officer","company":"ENGAGE XR Holdings","phone":"+16463155787","city":"New York City Zone 1","state":"NY","zip":"10001","address":None,"hubspot_owner_id":"","lifecyclestage":"lead","call_completed":"Meeting within 14 days","outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":"0","createdate":"2021-10-09T17:32:35.165Z","hs_v2_date_entered_current_stage":"2026-04-30T21:27:38.223Z","wealth_segment":"$1M-$2M","inferred_income":"$101k - $250k","hs_email_open":"2","hs_email_delivered":"2","hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"rcallinjr@gmail.com","pipl_linkedin":None}},
  {"id":"223243896949","properties":{"firstname":"Todd","lastname":"Schn","email":"plus_one_rsvp_toddschn@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.972Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.972Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"erin.culek@gmail.com","work_email":"Plus_One_RSVP_ToddSchn@gmail.com","pipl_linkedin":None}},
  {"id":"223244901459","properties":{"firstname":"christen","lastname":"douglas","email":"cdouglas@mcdermottlaw.com","jobtitle":"Partner","company":"McDermott & Mandery","phone":"+16196949084","city":"New York","state":"NY","zip":"10017","address":"1 Vanderbilt Avenue","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:47:46.872Z","hs_v2_date_entered_current_stage":"2026-05-22T13:47:46.872Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"cdouglas@mcdermottlaw.com","pipl_linkedin":None}},
  {"id":"102933021761","properties":{"firstname":"Sudeep","lastname":"Doshi","email":"sudeep.doshi@gmail.com","jobtitle":"Partner","company":"McKinsey & Company","phone":"6466628914","city":"New York City","state":"NY","zip":"10001","address":"3 World Trade Ctr 175","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2025-03-01T00:41:40.602Z","hs_v2_date_entered_current_stage":"2025-03-01T00:41:40.602Z","wealth_segment":"$5M+ TO $10M","inferred_income":"$501K - $1M","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"sudeep.doshi@gmail.con","hs_linkedin_url":"https://www.linkedin.com/in/sudeep-doshi-6a5a7b25","pipl_linkedin":"linkedin.com/in/sudeep-doshi-6a5a7b25"}},
  {"id":"224364188294","properties":{"firstname":"Melissa","lastname":"Berglass","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T21:36:59.110Z","hs_v2_date_entered_current_stage":"2026-05-27T21:37:17.670Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"223239909188","properties":{"firstname":"Jeanette","lastname":"Brown","email":"plus_one_rsvp_jeanettebrown@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"","outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.198Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.198Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"mark.mantione@gmail.com","work_email":"Plus_One_RSVP_JeanetteBrown@gmail.com","pipl_linkedin":None}},
  {"id":"224345827471","properties":{"firstname":"Katie","lastname":"O'Connor","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T21:17:40.776Z","hs_v2_date_entered_current_stage":"2026-05-27T21:17:59.152Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"223245171866","properties":{"firstname":"Bodhi","lastname":"Patel","email":"plus_one_rsvp_bodhipatel@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.766Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.766Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"abhilashgpatel@gmail.com","work_email":"Plus_One_RSVP_BodhiPatel@gmail.com","pipl_linkedin":None}},
  {"id":"223173738388","properties":{"firstname":"Justin","lastname":"Root","email":"plus_one_rsvp_justinroot@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.430Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.430Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"2bmatherman@gmail.com","work_email":"Plus_One_RSVP_JustinRoot@gmail.com","pipl_linkedin":None}},
  {"id":"223244677140","properties":{"firstname":"Tomer","lastname":None,"email":"plus_one_rsvp_tomer@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.767Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.767Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"tmarinovsky@gmail.com","work_email":"Plus_One_RSVP_Tomer@gmail.com","pipl_linkedin":None}},
  {"id":"289815051","properties":{"firstname":"Gerard","lastname":"Peyer","email":"simmes11@aol.com","jobtitle":None,"company":None,"phone":"+15166804782","city":"williston park","state":"NY","zip":"11040","address":"182 collins ave","hubspot_owner_id":"144178976","lifecyclestage":"customer","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":"Disqualified","unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":"0","createdate":"2022-07-20T16:16:22.539Z","hs_v2_date_entered_current_stage":"2022-08-15T15:08:09.067Z","wealth_segment":"$2M-$5M","inferred_income":"$101K - $250K","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"simmes11@aol.com","pipl_linkedin":None}},
  {"id":"223239288713","properties":{"firstname":"Mark","lastname":"Fulinara","email":"plus_one_rsvp_markfulinara@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.751Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.751Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"adam_imada@spe.sony.com","work_email":"Plus_One_RSVP_MarkFulinara@gmail.com","pipl_linkedin":None}},
  {"id":"223238437734","properties":{"firstname":"Clare","lastname":"Pickering","email":"plus_one_rsvp_clarepickering@gmail.com","jobtitle":"Director, Municipal Strategy","company":"Barclays","phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.253Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.253Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"joseph.t.clarke@gmail.com","work_email":"Plus_One_RSVP_ClarePickering@gmail.com","pipl_linkedin":None}},
  {"id":"223239656866","properties":{"firstname":"Adriana","lastname":"Gonzales","email":"plus_one_rsvp_adrianagonzales@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.750Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.750Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"charles@8otherreasons.com","work_email":"Plus_One_RSVP_AdrianaGonzales@gmail.com","pipl_linkedin":None}},
  {"id":"222556156541","properties":{"firstname":"Joseph","lastname":"Clarke","email":"joseph.t.clarke@gmail.com","jobtitle":"Founder & President","company":"Winged Foot Companies","phone":"5166554084","city":"glen head","state":None,"zip":None,"address":"73 brookville rd","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":"Disqualified","unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-19T18:22:53.079Z","hs_v2_date_entered_current_stage":"2026-05-19T18:22:53.079Z","wealth_segment":"$2M-$5M","inferred_income":"$101K - $250K","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"joseph.t.clarke@gmail.com","pipl_linkedin":None}},
  {"id":"223245887298","properties":{"firstname":"tomer","lastname":"marinovsky","email":"tmarinovsky@gmail.com","jobtitle":"Showroom Manager","company":"Poliform USA","phone":"+19173768006","city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.612Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.612Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"tmarinovsky@gmail.com","pipl_linkedin":None}},
  {"id":"223239543417","properties":{"firstname":"Chris","lastname":"Vidal","email":"upperwestskates@gmail.com","jobtitle":"Shop Owner","company":"Upper West Skates","phone":"+19172512244","city":"New York City","state":None,"zip":None,"address":"2768 Broadway","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.753Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.753Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"upperwestskates@gmail.com","pipl_linkedin":"https://www.linkedin.com/in/christophervidal"}},
  {"id":"223239258710","properties":{"firstname":"Kelly","lastname":"Patel","email":"plus_one_rsvp_kellypatel@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.252Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.252Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"abhilashgpatel@gmail.com","work_email":"Plus_One_RSVP_KellyPatel@gmail.com","pipl_linkedin":None}},
  {"id":"223246034527","properties":{"firstname":"Regina","lastname":"Cummings","email":"regina.cummings@dzbank.de","jobtitle":"Assistant Vice President","company":"DZ Bank","phone":"+16465442477","city":"New York City","state":None,"zip":None,"address":"609 5th Ave,Rm 601","hubspot_owner_id":"77771452","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":"Disqualified","unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.970Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.970Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"cummingsnyc@gmail.com","pipl_linkedin":"https://www.linkedin.com/in/reginacummings"}},
  {"id":"223239620670","properties":{"firstname":"Colton","lastname":"Pappas","email":"plus_one_rsvp_coltonpappas@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.231Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.231Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"charles@8otherreasons.com","work_email":"Plus_One_RSVP_ColtonPappas@gmail.com","pipl_linkedin":None}},
  {"id":"168751113342","properties":{"firstname":"Emily","lastname":"Dorin","email":"emily.dorin@accenture.com","jobtitle":"Principal Director","company":"Accenture","phone":"+16467174521","city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2025-10-27T21:56:29.926Z","hs_v2_date_entered_current_stage":"2025-10-27T21:56:29.926Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"emily.dorin@gmail.com","pipl_linkedin":None}},
  # ── Batch 2 ───────────────────────────────────────────────────────────────
  {"id":"224349365265","properties":{"firstname":"Judith","lastname":"Vargas","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"77771452","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T20:59:57.012Z","hs_v2_date_entered_current_stage":"2026-05-27T21:00:18.523Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"174209708604","properties":{"firstname":"Jennifer","lastname":"Coppola","email":"j.coppola@pure-trade.com","jobtitle":"Vice President, Sales & Business Development (US)","company":"Pure Trade","phone":"+16463713212","city":"New York City","state":None,"zip":None,"address":"347 5th Ave Rm 604","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2025-11-11T18:18:35.883Z","hs_v2_date_entered_current_stage":None,"wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"j.coppola@pure-trade.com","pipl_linkedin":None}},
  {"id":"223240072240","properties":{"firstname":"jamison","lastname":"davis","email":"jamison.davis@bountifulfinancial.com","jobtitle":"Chief Marketing Officer & Co-Founder","company":"Bountifulfinancial","phone":"+12038322875","city":None,"state":None,"zip":None,"address":"196 OLD KINGS HWY N","hubspot_owner_id":"73613833","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:47:47.067Z","hs_v2_date_entered_current_stage":"2026-05-26T21:23:06.162Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"jamison.davis@bountifulfinancial.com","pipl_linkedin":None}},
  {"id":"223239523593","properties":{"firstname":"Katie","lastname":"O'Connor","email":"plus_one_rsvp_katieo'connor@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.232Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.232Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"betsy.colucci@wellsfargo.com","work_email":"Plus_One_RSVP_KatieO'Connor@gmail.com","pipl_linkedin":None}},
  {"id":"223240624510","properties":{"firstname":"francis","lastname":"magdits","email":"plus_one_rsvp_francismagdits@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.968Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.968Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"j.coppola@pure-trade.com","work_email":"Plus_One_RSVP_francismagdits@gmail.com","pipl_linkedin":None}},
  {"id":"223239514486","properties":{"firstname":"Jina","lastname":None,"email":"plus_one_rsvp_jina@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.198Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.198Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"arashmoradzadeh@yahoo.com","work_email":"Plus_One_RSVP_Jina@gmail.com","pipl_linkedin":None}},
  {"id":"224334286966","properties":{"firstname":"kevin_foulds@yahoo.com","lastname":"Foulds","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"77771452","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T20:58:22.721Z","hs_v2_date_entered_current_stage":"2026-05-27T20:58:40.285Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"223240411493","properties":{"firstname":"Suhaib","lastname":"Bingaradi","email":"suhaibfaris@gmail.com","jobtitle":"Senior Vice President, Private Client","company":None,"phone":"+16464600987","city":"new york","state":None,"zip":None,"address":"20 exchange pl","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.270Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.270Z","wealth_segment":"$2M-$5M","inferred_income":"$251k - $500k","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"suhaibfaris@gmail.com","pipl_linkedin":"linkedin.com/in/suhaib-bingaradi"}},
  {"id":"223245861531","properties":{"firstname":"Camilo","lastname":"Villota","email":"plus_one_rsvp_camilovillota@gmail.com","jobtitle":"VP, Creative Director","company":"Wegmans Food Markets","phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.269Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.269Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"suhaibfaris@gmail.com","work_email":"Plus_One_RSVP_CamiloVillota@gmail.com","pipl_linkedin":None}},
  {"id":"224365697445","properties":{"firstname":"Dov","lastname":"Plawsky","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T22:28:38.174Z","hs_v2_date_entered_current_stage":"2026-05-27T22:28:55.889Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"223240784943","properties":{"firstname":"Luis","lastname":"Cabrera","email":"plus_one_rsvp_luiscabrera@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"77771452","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"","outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.231Z","hs_v2_date_entered_current_stage":"2026-05-27T20:38:56.395Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"age.kindest-6m@icloud.com","work_email":"Plus_One_RSVP_LuisCabrera@gmail.com","pipl_linkedin":None}},
  {"id":"156711503152","properties":{"firstname":"Matthew","lastname":"Berglass","email":"mberglass@berglassassociates.com","jobtitle":"President","company":"Berglass + Associates","phone":"9175923100","city":"New York City","state":"NY","zip":"10017","address":"250 Park Ave, 14th Fl","hubspot_owner_id":"77771452","lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2025-09-19T17:45:33.235Z","hs_v2_date_entered_current_stage":"2026-05-27T21:36:53.755Z","wealth_segment":"$20M+ TO $50M","inferred_income":"$501K - $1M","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"mberglass@berglassassociates.com","pipl_linkedin":"https://www.linkedin.com/in/matthew-berglass-4b484821"}},
  {"id":"224349822515","properties":{"firstname":"Min","lastname":"Park","email":None,"jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-27T21:09:05.778Z","hs_v2_date_entered_current_stage":"2026-05-27T21:09:25.850Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":None,"pipl_linkedin":None}},
  {"id":"223239279979","properties":{"firstname":"Bianca","lastname":"Kunth","email":"plus_one_rsvp_biancakunth@gmail.com","jobtitle":"Associate Director","company":"NordLB New York Branch","phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.466Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.466Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"cummingsnyc@gmail.com","work_email":"Plus_One_RSVP_BiancaKunth@gmail.com","pipl_linkedin":None}},
  {"id":"223238294079","properties":{"firstname":"Anna","lastname":"Daher","email":"anna.daher@fundraiseup.com","jobtitle":"Chief Financial Officer","company":"Fundraise Up","phone":"+16468123542","city":"New York City","state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.251Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.251Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"anna.daher@fundraiseup.com","pipl_linkedin":"https://www.linkedin.com/in/annadaher"}},
  {"id":"223244403035","properties":{"firstname":"j.","lastname":"vargas","email":"age.kindest-6m@icloud.com","jobtitle":None,"company":None,"phone":"+12129828929","city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"77771452","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":"Disqualified","unknown_rsvp":"Unknown","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.269Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.269Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"age.kindest-6m@icloud.com","pipl_linkedin":None}},
  {"id":"223245365891","properties":{"firstname":"Robin","lastname":"Chiang","email":"robinychiang@gmail.com","jobtitle":"Chief Growth Officer","company":"OpenTable","phone":"+18565180","city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.231Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.231Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"robinychiang@gmail.com","pipl_linkedin":None}},
  {"id":"394082051","properties":{"firstname":"Erin","lastname":"Leamon","email":"erin.leamon@gmail.com","jobtitle":"Chief Marketing & Business Development Officer","company":"Cohen & Gresser","phone":"+12128107734","city":"New York City Zone 1","state":"NY","zip":"10001","address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":"0","createdate":"2023-03-27T18:35:03.521Z","hs_v2_date_entered_current_stage":"2023-03-27T18:35:03.521Z","wealth_segment":"$2M-$5M","inferred_income":"$101k - $250k","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"erin.leamon@gmail.com","pipl_linkedin":None}},
  {"id":"223238634667","properties":{"firstname":"Mavourneen","lastname":None,"email":"plus_one_rsvp_mavourneen@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.431Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.431Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"simmes11@aol.com","work_email":"Plus_One_RSVP_Mavourneen@gmail.com","pipl_linkedin":None}},
  {"id":"203791451","properties":{"firstname":"M","lastname":"Littman","email":"mlittman@nledit.com","jobtitle":"Director, Partner","company":"Bodega Studios","phone":"+12122741199","city":"New York","state":"NY","zip":"10011","address":"245 W 19th Street 8N","hubspot_owner_id":"73613833","lifecyclestage":"customer","call_completed":"Meeting within 14 days","outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"Yes","outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":"0","createdate":"2022-03-01T12:38:40.609Z","hs_v2_date_entered_current_stage":None,"wealth_segment":"$500K-$1M","inferred_income":"$101k - $250k","hs_email_open":"1","hs_email_delivered":"8","hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"mlittman@nledit.com","pipl_linkedin":"https://www.linkedin.com/in/david-gioiella-a51b9b3"}},
  {"id":"133879700628","properties":{"firstname":"Mark","lastname":"f","email":"mark.mantione@gmail.com","jobtitle":"CEO, North America","company":"Metrica","phone":"2033559891","city":"greenwich","state":"CT","zip":None,"address":"174 weaver st","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2025-07-01T13:56:43.471Z","hs_v2_date_entered_current_stage":"2025-07-01T13:56:43.471Z","wealth_segment":"$2M-$5M","inferred_income":"$101K - $250K","hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"mark.mantione@gmail.com","pipl_linkedin":None}},
  {"id":"223245233716","properties":{"firstname":"Melissa","lastname":"Berglass","email":"plus_one_rsvp_melissaberglass@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"opportunity","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":"","outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.910Z","hs_v2_date_entered_current_stage":"2026-05-27T21:37:55.405Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"mberglass@berglassassociates.com","work_email":"Plus_One_RSVP_MelissaBerglass@gmail.com","pipl_linkedin":None}},
  {"id":"223239592037","properties":{"firstname":"Michael","lastname":"Holman","email":"plus_one_rsvp_michaelholman@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.231Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.231Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"beverlyp@starinc.org","work_email":"Plus_One_RSVP_MichaelHolman@gmail.com","pipl_linkedin":None}},
  {"id":"223239042478","properties":{"firstname":"Danielle","lastname":"Parisi","email":"plus_one_rsvp_danielleparisi@gmail.com","jobtitle":"VP, Sales","company":"G-III Apparel Group","phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.198Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.198Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"bparisi2002@gmail.com","work_email":"Plus_One_RSVP_DanielleParisi@gmail.com","pipl_linkedin":None}},
  {"id":"223240088889","properties":{"firstname":"Archer","lastname":"Patel","email":"plus_one_rsvp_archerpatel@gmail.com","jobtitle":None,"company":None,"phone":None,"city":None,"state":None,"zip":None,"address":None,"hubspot_owner_id":None,"lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Guest","outbound_event_send_confirmation":None,"totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.252Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.252Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":"abhilashgpatel@gmail.com","work_email":"Plus_One_RSVP_ArcherPatel@gmail.com","pipl_linkedin":None}},
  {"id":"223243933030","properties":{"firstname":"Tugba","lastname":"Colpan","email":"tugba.colpan@enquire.ai","jobtitle":"Chief Commercial Officer (Cco)","company":"Enquire AI","phone":"+19178159612","city":"New York City","state":None,"zip":None,"address":None,"hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":None,"outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:43.431Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:43.431Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"tcolpan@gmail.com","pipl_linkedin":"https://www.linkedin.com/in/tugba-colpan-26954a52"}},
  {"id":"223243933024","properties":{"firstname":"Erin","lastname":"Culek","email":"erin.culek@gmail.com","jobtitle":"Financial Protection & Retirement Solutions Head","company":"Guardian Insurance","phone":"+19172942012","city":"New York City","state":None,"zip":None,"address":"10 Hudson Yards","hubspot_owner_id":"202057506","lifecyclestage":"lead","call_completed":None,"outbound_rsvp_to_event":"2026-05-27","attended_outbound_event":None,"outbound_event_attendee_disqualified":None,"unknown_rsvp":"Unknown","outbound_event_send_confirmation":"Yes","totalamountpurchased":None,"createdate":"2026-05-22T13:49:42.969Z","hs_v2_date_entered_current_stage":"2026-05-22T13:49:42.969Z","wealth_segment":None,"inferred_income":None,"hs_email_open":None,"hs_email_delivered":None,"hs_email_first_reply_date":None,"outbound_event_host_name":None,"work_email":"erin.culek@gmail.com","pipl_linkedin":"https://www.linkedin.com/in/erinculek"}},
]

# Apply enrichments (only fill blank fields)
for c in CONTACTS:
    enrichment = ENRICHMENTS.get(c["id"])
    if enrichment:
        for k, v in enrichment.items():
            if not c["properties"].get(k):
                c["properties"][k] = v
        print(f"[ENRICH] {c['properties'].get('firstname')} {c['properties'].get('lastname','')}: {enrichment}")

MOCK_RESPONSE_MAIN = {"results": CONTACTS, "paging": {}}

# ── Monkeypatch requests ─────────────────────────────────────────────────────
import requests as _req

_orig_post  = _req.post
_orig_patch = _req.patch
_orig_get   = _req.get

SEARCH_URL = 'https://api.hubapi.com/crm/v3/objects/contacts/search'

class _R:
    def __init__(self, data=None, sc=200):
        self._data = data or {}
        self.status_code = sc
        self.ok = sc < 400
    def json(self):    return self._data
    def raise_for_status(self):
        if not self.ok: raise Exception(f'HTTP {self.status_code}')

def _mock_post(url, *args, **kwargs):
    if SEARCH_URL in (url or ''):
        payload = kwargs.get('json', {})
        for fg in payload.get('filterGroups', []):
            for f in fg.get('filters', []):
                if f.get('propertyName') == 'outbound_rsvp_to_event':
                    return _R(MOCK_RESPONSE_MAIN)
        return _R({"results": []})  # host-lookup and other searches
    # Block batch email reads etc. — return empty
    return _R({"results": []})

def _mock_patch(url, *args, **kwargs):
    body = kwargs.get('json', {})
    print(f'[SKIP-PATCH] {url.split("/")[-1]} → {body}')
    return _R({"id": url.split("/")[-1]})

def _mock_get(url, *args, **kwargs):
    # Allow public NYC PLUTO endpoint (cityofnewyork.us) — may work
    if 'cityofnewyork.us' in (url or ''):
        try: return _orig_get(url, *args, **kwargs)
        except: pass
    # Allow Census API
    if 'census.gov' in (url or ''):
        try: return _orig_get(url, *args, **kwargs)
        except: pass
    # Block everything else (LinkedIn, GitHub Gist, RocketReach, etc.)
    return _R({}, 403)

_req.post  = _mock_post
_req.patch = _mock_patch
_req.get   = _mock_get

# ── Run the generator ────────────────────────────────────────────────────────
import generate_rsvp
generate_rsvp.main()
